/// Inference metrics captured from a single LLM generation call.
#[derive(Debug, Clone)]
pub struct InferenceMetrics {
    /// Tokens consumed as input (system prompt + user message + history).
    pub tokens_in: u32,
    /// Tokens generated by the model.
    pub tokens_out: u32,
    /// Model identifier reported by the backend.
    pub model_id: String,
    /// Total latency of the inference call (wall clock).
    pub latency_ms: u64,
}

impl InferenceMetrics {
    pub fn new(
        tokens_in: u32,
        tokens_out: u32,
        model_id: impl Into<String>,
        latency_ms: u64,
    ) -> Self {
        Self {
            tokens_in,
            tokens_out,
            model_id: model_id.into(),
            latency_ms,
        }
    }

    /// Estimate cost in cents. LM Studio local inference is "free" (zero marginal).
    pub fn estimated_cost_cents(&self) -> f64 {
        0.0
    }
}
